name: Windows RDP Free (4H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Launching RDP & Localtonet Connection
        shell: powershell
        run: |
          # إعداد نظام التحكم عن بعد وكلمة المرور في الويندوز
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user runneradmin "Password123!"
          
          # تحميل وتثبيت أداة التانيل الحرة والتلقائية
          Invoke-WebRequest -Uri "https://localtonet.com" -OutFile "localtonet.zip"
          Expand-Archive -Path "localtonet.zip" -DestinationPath "."
          
          # تشغيل الاتصال المباشر لـ RDP بدون حظر أو تفعيل بطاقات
          Write-Host "Starting Free RDP Tunnel via Localtonet..."
          .\localtonet.exe -authtoken "HbNDJfOd7X86uThBeEF34q2ZRAjnwgWi5" -protocol tcp -port 3389

