name: Windows RDP Free (4H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Launching RDP via Cloudflare Tunnel
        shell: powershell
        run: |
          # 1. إعداد نظام التحكم عن بعد وكلمة المرور في الويندوز
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user runneradmin "Password123!"
          
          # 2. تثبيت أداة كلوود فلير الرسمية تلقائياً عبر مدير الحزم Choco
          choco install cloudflared --no-progress -y
          
          # 3. تشغيل نفق RDP مجاني ومستقر تلقائياً والانتظار لتوليد الرابط
          Write-Host "Starting Secure Cloudflare RDP Tunnel..."
          cloudflared tunnel --url rdp://localhost:3389
